- name: Nova Install
  apt:
    name:
      - nova-compute
      - python3-openstackclient
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Initiallizing Nova
  service:
    name: nova-compute
    state: restarted
    enabled: yes
